# Generated by Django 5.2.1 on 2025-09-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='students/')),
            ],
        ),
    ]
