# Generated by Django 5.2.1 on 2025-09-12 03:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate, editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='asistencia.student')),
            ],
            options={
                'verbose_name': 'Asistencia (Ingreso)',
                'verbose_name_plural': 'Asistencias (Ingresos)',
                'indexes': [models.Index(fields=['date'], name='asistencia__date_ac9c65_idx'), models.Index(fields=['student', 'date'], name='asistencia__student_b53f1c_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='uniq_attendance_student_date')],
            },
        ),
    ]
