# Generated by Django 5.2.1 on 2025-09-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='asistencia__date_ac9c65_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='asistencia__student_b53f1c_idx',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
