# Generated by Django 5.2.1 on 2025-09-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dni',
            field=models.CharField(max_length=8, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='student',
            name='numero',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='uniq_attendance_student_date'),
        ),
        migrations.DeleteModel(
            name='CheckOut',
        ),
    ]
